require('keymaps.code-edit-mappings')
-- require('config.keymaps.code-clean-mappings')
-- require('config.keymaps.buffer-mappings')
require('keymaps.telescope-keymaps')
-- require('config.keymaps.other-mappings')
-- require('config.keymaps.personal-mappings')
-- require('config.keymaps.git-mappings')
